### ISSUE TITLE
Add sql filter while provisioning topic subscription

### ISSUE THREAD

**Issue by CrazyTuna** [sjkp/Azure.ARM.ServiceBus#1]
Just wanted to know if it is possible to add rule (SQL filter) in the template to provision the topic subscription ?

Cheers,

**Comment by adeb0112** [comment]
Read about subscription filters here : 
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-create-topics-subscriptions

**Comment by CrazyTuna** [comment]
It is now supported:
[Create a Service Bus Namespace and Topic with a Subscription using a SQL Filter](https://github.com/Azure/azure-quickstart-templates/tree/master/101-servicebus-topic-subscription-sqlfilter)
